import { Router } from 'express';
import authRoutes from './auth/auth.routes.js';
import freelancerRoutes from './freelancer/freelancer.routes.js';
import clientRoutes from './client/client.routes.js';
import investorRoutes from './investor/investor.routes.js';
import founderRoutes from './founder/founder.routes.js';
import chatRoutes from './chat/chat.routes.js';
import notificationRoutes from './notifications/notifications.routes.js';
import fileRoutes from './files/files.routes.js';
import searchRoutes from './search/search.routes.js';
import discoveryRoutes from './discovery/discovery.routes.js';
import favoritesRoutes from './favorites/favorites.routes.js';
import systemRoutes from './system/system.routes.js';
import appRoutes from './app/app.routes.js';
const router = Router();
router.use('/auth', authRoutes);
router.use('/freelancer', freelancerRoutes);
router.use('/client', clientRoutes);
router.use('/investor', investorRoutes);
router.use('/founder', founderRoutes);
router.use('/chat', chatRoutes);
router.use('/notifications', notificationRoutes);
router.use('/files', fileRoutes);
router.use('/search', searchRoutes);
router.use('/discovery', discoveryRoutes);
router.use('/favorites', favoritesRoutes);
router.use('/system', systemRoutes);
router.use('/app', appRoutes);
export default router;
