"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_js_1 = __importDefault(require("./auth.routes.js"));
const public_routes_js_1 = __importDefault(require("./public.routes.js"));
const app_config_routes_js_1 = __importDefault(require("./app-config.routes.js"));
const system_routes_js_1 = __importDefault(require("./system.routes.js"));
const client_routes_js_1 = __importDefault(require("./client.routes.js"));
const freelancer_routes_js_1 = __importDefault(require("./freelancer.routes.js"));
const investor_routes_js_1 = __importDefault(require("./investor.routes.js"));
const founder_routes_js_1 = __importDefault(require("./founder.routes.js"));
const notifications_routes_js_1 = __importDefault(require("./notifications.routes.js"));
const messages_routes_js_1 = __importDefault(require("./messages.routes.js"));
const subscriptions_routes_js_1 = __importDefault(require("./subscriptions.routes.js"));
const wallet_routes_js_1 = __importDefault(require("./wallet.routes.js"));
const invoices_routes_js_1 = __importDefault(require("./invoices.routes.js"));
const support_routes_js_1 = __importDefault(require("./support.routes.js"));
const files_routes_js_1 = __importDefault(require("./files.routes.js"));
const payments_routes_js_1 = __importDefault(require("./payments.routes.js"));
const search_routes_js_1 = __importDefault(require("./search.routes.js"));
const discovery_routes_js_1 = __importDefault(require("./discovery.routes.js"));
const favorites_routes_js_1 = __importDefault(require("./favorites.routes.js"));
const chat_routes_js_1 = __importDefault(require("./chat.routes.js"));
const router = (0, express_1.Router)();
router.use('/auth', auth_routes_js_1.default);
router.use('/public', public_routes_js_1.default);
router.use('/app', app_config_routes_js_1.default);
router.use('/system', system_routes_js_1.default);
router.use('/client', client_routes_js_1.default);
router.use('/freelancer', freelancer_routes_js_1.default);
router.use('/investor', investor_routes_js_1.default);
router.use('/founder', founder_routes_js_1.default);
router.use('/notifications', notifications_routes_js_1.default);
router.use('/messages', messages_routes_js_1.default);
router.use('/subscriptions', subscriptions_routes_js_1.default);
router.use('/wallet', wallet_routes_js_1.default);
router.use('/invoices', invoices_routes_js_1.default);
router.use('/support', support_routes_js_1.default);
router.use('/files', files_routes_js_1.default);
router.use('/payments', payments_routes_js_1.default);
router.use('/search', search_routes_js_1.default);
router.use('/discovery', discovery_routes_js_1.default);
router.use('/favorites', favorites_routes_js_1.default);
router.use('/chat', chat_routes_js_1.default);
exports.default = router;
